### ISSUE TITLE
Missing Qt version check

### ISSUE THREAD

**Issue by krop** [bernds/q5Go#22]
While packaging q5Go in openSUSE, we noticed it fails to build with Qt < 5.10 due to QMetaObject::invokeMethod (https://doc.qt.io/qt-5/qmetaobject.html#invokeMethod-4 specifically).

The `configure` file only looks for the pkgconfig modules but doesn't define a minimum version for Qt dependencies.

**Comment by bernds** [comment]
I recommend using qmake rather than the configure file. It has support for packaging the README with pandoc, and the automake system doesn't. But that probably doesn't check the version either.

**Comment by krop** [comment]
Indeed, q5go.pro also doesn't set the minimum version

**Comment by bernds** [comment]
Hmm. There's this: https://doc.qt.io/qt-5/qmake-test-function-reference.html#versionatleast-variablename-versionnumber
But apparently it was added in Qt 5.10, so not much would be gained by adding that kind of test to the qmake file.

Is this actually a problem for openSUSE? Or more of a minor thing that will solve itself over time?

**Comment by krop** [comment]
Well, I can't build the package for openSUSE Leap 15.0 and 15.1 (the 2 versions currently supported). It builds nicely for Tumbleweed (our rolling release).

You can add:
```
lessThan(QT_MINOR_VERSION, 10) {
  error("At least Qt 5.10.0 is required to build q5Go")
}
```
in qbs.pro

**Comment by hanysz** [comment]
Trying to build on Ubuntu 18.04, I'm getting this error message.  Is it by any chance the same issue?

```
../src/gametree.cpp:129:103: error: no matching function for call to ‘QMetaObject::invokeMethod(GameTree*, void (GameTree::*)(), Qt::ConnectionType)’
 ) { QMetaObject::invokeMethod (this, &GameTree::resize_header, Qt::QueuedConnection); });
```

**Comment by hanysz** [comment]
Yes, it's the same thing.  I've just upgraded to Qt 5.12 (which was in itself a saga), and now I'm able to build with no errors.

**Comment by bernds** [comment]
If you wish, please try with current master to see if the issue is fixed. I've chosen to simply disable headers in the game tree for Qt 5.9 and below.

**Comment by krop** [comment]
> If you wish, please try with current master to see if the issue is fixed. I've chosen to simply disable headers in the game tree for Qt 5.9 and below.

It fails with another error now:

> temp_/ui_preferences_gui.h:2316:54: error: 'PlaceholderText' is not a member of 'QPalette'

which was added in Qt 5.12

**Comment by bernds** [comment]
That one is strange. Newer versions of designer add these unasked, but I remove them whenever they creep in. If I grep the tree, I see no instances of PlaceholderText, so I'm really not sure where they could be coming from. Were you building in a fresh build directory with a clean checkout, or is there a chance that your temp_/ui_preferences_gui.h was created by a newer version of Qt?

**Comment by krop** [comment]
No, the packaging build hosts never reuse older build environnements
However:
> q5Go-q5go-0.9/src # grep -ri PlaceholderText
> preferences_gui.ui:              <colorrole role="PlaceholderText">
> preferences_gui.ui:              <colorrole role="PlaceholderText">
> preferences_gui.ui:              <colorrole role="PlaceholderText">

**Comment by krop** [comment]
Commit 2fe4a0d8 was pushed after the 0.9 tagging.

**Comment by bernds** [comment]
Yes... the 0.9 release obviously won't change anymore. The current master branch has the fix for the QMetaObject::invokeMethod problem, I was hoping you could test whether that one works for you.

**Comment by krop** [comment]
I'm applying patches on top of the 0.9 release.
After applying the 2 commits above, the next issue is 
```
[   83s] In file included from temp_/moc_gametree.cpp:9:0:
[   83s] temp_/../gametree.h:16:14: error: 'shared_ptr' in namespace 'std' does not name a template type
[   83s]  typedef std::shared_ptr<game_record> go_game_ptr;
[   83s]               ^~~~~~~~~~
[   83s] temp_/../gametree.h:38:2: error: 'go_game_ptr' does not name a type
[   83s]   go_game_ptr m_game {};
[   83s]   ^~~~~~~~~~~
[   83s] temp_/../gametree.h:63:15: error: 'go_game_ptr' has not been declared
[   83s]   void update (go_game_ptr gr, game_state *, bool force = false);
[   83s]                ^~~~~~~~~~~
```

**Comment by bernds** [comment]
I'm adding the <memory> include. Why iostream though?

**Comment by krop** [comment]
> I'm adding the include. Why iostream though?

for the `std` namespace. The compiler probably won't complain if it's missing

**Comment by bernds** [comment]
There's no need for iostream there.
I'll assume this issue is fixed for now, please reopen if something creeps in again.
